version: '3'

services:
  db:
    image: postgres:14
    container_name: db_cofemaniya
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data


  backend:
    container_name: cofemaniya_backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    build: .